Create database CSDL_QUANLYHOTICH
drop database CSDL_QLHT_Test_2
Use CSDL_QUANLYHOTICH

CREATE TABLE THANHPHO(
	THANHPHO_ID  INT PRIMARY KEY IDENTITY(1,1),
	THANHPHO_TEN NVARCHAR(50),
	THANHPHO_TENCOQUAN NVARCHAR(100),
	THANHPHO_TRANGTHAI INT,
)
GO
CREATE TABLE QUAN(
	QUAN_ID  INT PRIMARY KEY IDENTITY(1,1),
	THANHPHO_ID INT,
	QUAN_TEN NVARCHAR(50),
	QUAN_TENCOQUAN NVARCHAR(100),
	QUAN_TRANGTHAI INT,
)
GO
ALTER TABLE QUAN
ADD CONSTRAINT FK_QUAN_THANHPHO FOREIGN KEY (THANHPHO_ID) REFERENCES THANHPHO(THANHPHO_ID)
GO
CREATE TABLE PHUONG(
	PHUONG_ID  INT IDENTITY(1,1),
	QUAN_ID INT,
	PHUONG_TEN NVARCHAR(50),
	PHUONG_TENCOQUAN NVARCHAR(100),
	PHUONG_TRANGTHAI INT,
)
GO
ALTER TABLE PHUONG
ADD CONSTRAINT PK_PHUONG PRIMARY KEY (PHUONG_ID)
ALTER TABLE PHUONG
ADD CONSTRAINT FK_PHUONG_QUAN FOREIGN KEY (QUAN_ID) REFERENCES QUAN(QUAN_ID)
GO


CREATE TABLE COQUAN(
	COQUAN_ID INT IDENTITY(1,1),
	COQUAN_TEN NVARCHAR(255),
	COQUAN_SDT NVARCHAR(11),
	COQUAN_EMAIL NVARCHAR(50),
	COQUAN_DIACHI NVARCHAR(255),
	COQUAN_GIOITHIEU NVARCHAR(255),
);

CREATE TABLE NGUOIDUNG(
	NGUOIDUNG_ID INT IDENTITY(1,1) PRIMARY KEY,
	NGUOIDUNG_MACANBO NVARCHAR(20),
	NGUOIDUNG_HOVATEN NVARCHAR(255),
	NGUOIDUNG_NGAYSINH DATE,
	NGUOIDUNG_EMAIL NVARCHAR(50),
	NGUOIDUNG_SDT NVARCHAR(11),
	NGUOIDUNG_USERNAME NVARCHAR(50),
	NGUOIDUNG_PASS NVARCHAR(20),
	NGUOIDUNG_TRANGTHAI INT,
	NGUOIDUNG_QUYEN INT,
	COQUAN_ID INT,
)
GO
CREATE TABLE LOAI_GIAYTO(
	LOAI_GIAYTO_ID INT IDENTITY(1,1),
	LOAI_GIAYTO_TEN NVARCHAR(50),
)
CREATE TABLE HOSO_DANGKY(
	HOSO_DANGKY_ID INT IDENTITY(1,1),
	HOSO_DANGKY_MA NVARCHAR(20),
	TRANGTHAI_XULY_ID INT,
	HOSO_DANGKY_NGAY_DANGKY DATE,
	HOSO_DANGKY_NGAY_HETHAN DATE,
	HOSO_DANGKY_EMAIL nvarchar(100),
	HOSO_DANGKY_SDT nvarchar,
	COQUAN_ID INT
)

--Thêm khóa chính và khóa ngoại
ALTER TABLE COQUAN
ADD CONSTRAINT	PK_COQUAN PRIMARY KEY (COQUAN_ID)
GO

ALTER TABLE LOAI_GIAYTO
ADD CONSTRAINT	PK_LOAI_GIAYTO PRIMARY KEY (LOAI_GIAYTO_ID)
GO
ALTER TABLE HOSO_DANGKY
ADD CONSTRAINT	PK_HOSO_DANGKY PRIMARY KEY (HOSO_DANGKY_ID)
GO



--Thêm khóa ngoại cho Hồ sơ đăng kí - Cơ quan
ALTER TABLE HOSO_DANGKY
ADD CONSTRAINT FK_HOSO_DANKY_COQUAN FOREIGN KEY (COQUAN_ID) REFERENCES COQUAN(COQUAN_ID)
GO
--Thêm khóa ngoại cho Người dùng - Cơ quan
ALTER TABLE NGUOIDUNG
ADD CONSTRAINT FK_NGUOIDUNG_COQUAN FOREIGN KEY (COQUAN_ID) REFERENCES COQUAN(COQUAN_ID)
GO

-- Tạo bảng Hình thức đăng kí
CREATE TABLE HINHTHUC_DANGKY(
	HINHTHUC_DANGKY_ID INT IDENTITY(1,1),
	HINHTHUC_DANGKY_TEN NVARCHAR(255),
)
--Tạo bảng Loại đăng kí
CREATE TABLE LOAI_DANGKY(
	LOAI_DANGKY_ID INT IDENTITY(1,1),
	LOAI_GIAYTO_ID INT,
	HINHTHUC_DANGKY_ID INT,
	LOAI_DANGKY_TEN NVARCHAR(255),
	LOAI_DANGKY_HANXULY INT,
	LOAI_DANGKY_LEPHI MONEY,
)
--Thiết lập khóa chính cho Hình thức đăng kí và loại đăng kí
ALTER TABLE HINHTHUC_DANGKY
ADD CONSTRAINT	PK_HINHTHUC_DANGKY PRIMARY KEY (HINHTHUC_DANGKY_ID)
GO
ALTER TABLE LOAI_DANGKY
ADD CONSTRAINT	PK_LOAI_DANGKY PRIMARY KEY (LOAI_DANGKY_ID)
GO
--Thêm khóa ngoại cho Hồ sơ đăng kí - Loại đăng kí
ALTER TABLE HOSO_DANGKY
ADD LOAI_DANGKY_ID INT;
GO
ALTER TABLE HOSO_DANGKY
ADD CONSTRAINT FK_HOSO_DANGKY_LOAI_DANGKY FOREIGN KEY (LOAI_DANGKY_ID) REFERENCES LOAI_DANGKY(LOAI_DANGKY_ID)
GO
--Thêm khóa ngoại cho Loại đăng kí - Loại giấy tờ
ALTER TABLE LOAI_DANGKY
ADD CONSTRAINT FK_LOAI_DANGKY_LOAI_GIAYTO FOREIGN KEY (LOAI_GIAYTO_ID) REFERENCES LOAI_GIAYTO(LOAI_GIAYTO_ID)
GO
--Thêm khóa ngoại cho Loại đăng kí - Hình thức đăng kí
ALTER TABLE LOAI_DANGKY
ADD CONSTRAINT FK_LOAI_DANGKY_HINHTHUC_DANGKY FOREIGN KEY (HINHTHUC_DANGKY_ID) REFERENCES HINHTHUC_DANGKY(HINHTHUC_DANGKY_ID)
GO

CREATE TABLE DANTOC(
	DANTOC_ID INT IDENTITY(1,1),
	DANTOC_TEN NVARCHAR(50),
)
ALTER TABLE DANTOC
ADD CONSTRAINT PK_DANTOC PRIMARY KEY (DANTOC_ID)

CREATE TABLE QUOCGIA(
	QUOCGIA_ID INT IDENTITY(1,1),
	QUOCGIA_TEN NVARCHAR(50),
)
ALTER TABLE QUOCGIA
ADD CONSTRAINT PK_QUOCGIA PRIMARY KEY (QUOCGIA_ID)

-- Các loại giấy tờ

CREATE TABLE DANGKY_KHAISINH(
	HOSO_DANGKY_ID INT NOT NULL,

	NGUOIYEUCAU_TEN NVARCHAR(255),
	NGUOIYEUCAU_CMND NVARCHAR(12),
	NGUOIYEUCAU_CMND_NGAYCAP DATE,
	NGUOIYEUCAU_CMND_NOICAP NVARCHAR(255),
	NGUOIYEUCAU_QUOCTICH NVARCHAR(50),

	--Địa chỉ người yêu cầu
	NGUOIYEUCAU_THANHPHO NVARCHAR(50),
	NGUOIYEUCAU_QUAN NVARCHAR(50),
	NGUOIYEUCAU_PHUONG NVARCHAR(50),
	NGUOIYEUCAU_DIACHI NVARCHAR(255),

	NGUOIYEUCAU_QUANHE NVARCHAR(100),

	KHAISINH_TEN NVARCHAR(255),
	KHAISINH_GIOITINH BIT,
	KHAISINH_NGAYSINH DATE,
	KHAISINH_DANTOC NVARCHAR(50),
	KHAISINH_QUOCTICH NVARCHAR(50),

	--Quê quán
	KHAISINH_QUEQUAN_THANHPHO NVARCHAR(50),
	KHAISINH_QUEQUAN_QUAN NVARCHAR(50), 
	KHAISINH_QUEQUAN_PHUONG NVARCHAR(50),
	KHAISINH_QUEQUAN_DIACHI NVARCHAR(255),

	--Nơi sinh
	KHAISINH_NOISINH NVARCHAR(100), 
	KHAISINH_NOISINH_QUOCGIA NVARCHAR(50),
	KHAISINH_NOISINH_THANHPHO NVARCHAR(50), 
	KHAISINH_NOISINH_QUAN NVARCHAR(50),
	KHAISINH_NOISINH_PHUONG NVARCHAR(50), 
	KHAISINH_NOISINH_DIACHI NVARCHAR(255), 

	ME_TEN NVARCHAR(255),
	ME_NGAYSINH DATE,
	ME_DANTOC NVARCHAR(50),
	ME_CMND NVARCHAR(12),
	ME_CMND_NGAYCAP DATE,
	ME_CMND_NOICAP NVARCHAR(255),
	ME_QUOCTICH NVARCHAR(50),
	--Địa chỉ của mẹ
	ME_THANHPHO NVARCHAR(50),
	ME_QUAN NVARCHAR(50),
	ME_PHUONG NVARCHAR(50),
	ME_DIACHI NVARCHAR(255),

	CHA_TEN NVARCHAR(255),
	CHA_NGAYSINH DATE,
	CHA_DANTOC NVARCHAR(50),
	CHA_CMND NVARCHAR(12),
	CHA_CMND_NGAYCAP DATE,
	CHA_CMND_NOICAP NVARCHAR(255),
	CHA_QUOCTICH NVARCHAR(50),
	--Địa chỉ của cha
	CHA_THANHPHO NVARCHAR(50),
	CHA_QUAN NVARCHAR(50),
	CHA_PHUONG NVARCHAR(50),
	CHA_DIACHI NVARCHAR(255),

	FILE_GIAYCHUNGSINH NVARCHAR(255)
)
GO
ALTER TABLE DANGKY_KHAISINH
ADD CONSTRAINT PK_DANGKY_KHAISINH PRIMARY KEY (HOSO_DANGKY_ID)
GO
ALTER TABLE DANGKY_KHAISINH
ADD CONSTRAINT FK_DANGKY_KHAISINH_HOSO_DANG_KY FOREIGN KEY (HOSO_DANGKY_ID) REFERENCES HOSO_DANGKY(HOSO_DANGKY_ID)
GO

CREATE TABLE DANGKY_KETHON(
	HOSO_DANGKY_ID INT  NOT NULL,

	KETHON_V_HOTEN NVARCHAR(255),
	KETHON_V_NGAYSINH DATE,
	KETHON_V_DANTOC NVARCHAR(50),
	KETHON_V_CMND NVARCHAR(12),
	KETHON_V_CMND_NGAYCAP DATE,
	KETHON_V_CMND_NOICAP NVARCHAR(255),

	KETHON_V_QUOCTICH NVARCHAR(50),

	KETHON_V_THANHPHO NVARCHAR(50),
	KETHON_V_QUAN NVARCHAR(50),
	KETHON_V_PHUONG NVARCHAR(50),
	KETHON_V_DIACHI NVARCHAR(255),
	KETHON_V_LAN INT,
	KETHON_FILE_V NVARCHAR(255),

	KETHON_C_HOTEN NVARCHAR(255),
	KETHON_C_NGAYSINH DATE,
	KETHON_C_DANTOC NVARCHAR(50),
	KETHON_C_CMND NVARCHAR(12),
	KETHON_C_CMND_NGAYCAP DATE,
	KETHON_C_CMND_NOICAP NVARCHAR(255),
	KETHON_C_QUOCTICH NVARCHAR(50),
	KETHON_C_THANHPHO NVARCHAR(50),
	KETHON_C_QUAN NVARCHAR(50),
	KETHON_C_PHUONG NVARCHAR(50),
	KETHON_C_DIACHI NVARCHAR(255),
	KETHON_C_LAN INT,
	KETHON_FILE_C NVARCHAR(255),

)
GO
ALTER TABLE DANGKY_KETHON
ADD CONSTRAINT PK_DANGKY_KETHON PRIMARY KEY (HOSO_DANGKY_ID)
GO
ALTER TABLE DANGKY_KETHON
ADD CONSTRAINT FK_DANGKY_KETHON_HOSO_DANG_KY FOREIGN KEY (HOSO_DANGKY_ID) REFERENCES HOSO_DANGKY(HOSO_DANGKY_ID)
GO


CREATE TABLE DANGKY_CHUNGTU(
	HOSO_DANGKY_ID INT  NOT NULL,

	NGUOIYEUCAU_TEN NVARCHAR(255),
	NGUOIYEUCAU_CMND NVARCHAR(12),
	NGUOIYEUCAU_CMND_NGAYCAP DATE,
	NGUOIYEUCAU_CMND_NOICAP NVARCHAR(255),
	NGUOIYEUCAU_QUOCTICH NVARCHAR(50),
	NGUOIYEUCAU_THANHPHO NVARCHAR(50),
	NGUOIYEUCAU_QUAN NVARCHAR(50),
	NGUOIYEUCAU_PHUONG NVARCHAR(50),
	NGUOIYEUCAU_DIACHI NVARCHAR(50),

	NGUOIYEUCAU_QUANHE NVARCHAR(100),

	KHAITU_TEN NVARCHAR(100),
	KHAITU_NGAYSINH DATE,
	KHAITU_GIOITINH BIT,
	KHAITU_DANTOC NVARCHAR(50),
	KHAITU_CMND NVARCHAR(12),
	KHAITU_CMND_NGAYCAP DATE,
	KHAITU_CMND_NOICAP NVARCHAR(255),
	KHAITU_QUOCTICH NVARCHAR(50),
	KHAITU_THANHPHO NVARCHAR(50),
	KHAITU_QUAN NVARCHAR(50),
	KHAITU_PHUONG NVARCHAR(50),
	KHAITU_DIACHI NVARCHAR(255),

	KHAITU_NGUYENNHAN NVARCHAR(255),
	KHAITU_NGAYMAT DATE,
	KHAITU_THOIGIAN TIME,
	KHAITU_NOIMAT_QUOCGIA NVARCHAR(50),
	KHAITU_NOIMAT_THANHPHO NVARCHAR(50),
	KHAITU_NOIMAT_QUAN NVARCHAR(50),
	KHAITU_NOIMAT_PHUONG NVARCHAR(50),
	KHAITU_NOIMAT_DIACHI NVARCHAR(255),
    
	FILE_BAOTU_TEN NVARCHAR(255)

)
GO
ALTER TABLE DANGKY_CHUNGTU
ADD CONSTRAINT PK_DANGKY_CHUNGTU PRIMARY KEY (HOSO_DANGKY_ID)
GO
ALTER TABLE DANGKY_CHUNGTU
ADD CONSTRAINT FK_DANGKY_CHUNGTU_HOSO_DANG_KY FOREIGN KEY (HOSO_DANGKY_ID) REFERENCES HOSO_DANGKY(HOSO_DANGKY_ID)
GO

CREATE TABLE DANGKY_TRICHLUC(
	HOSO_DANGKY_ID INT NOT NULL,

	NGUOIYEUCAU_TEN NVARCHAR(255),
	NGUOIYEUCAU_CMND NVARCHAR(12),
	NGUOIYEUCAU_CMND_NGAYCAP DATE,
	NGUOIYEUCAU_CMND_NOICAP NVARCHAR(255),
	NGUOIYEUCAU_QUOCTICH NVARCHAR(50),
	NGUOIYEUCAU_THANHPHO NVARCHAR(50),
	NGUOIYEUCAU_QUAN NVARCHAR(50),
	NGUOIYEUCAU_PHUONG NVARCHAR(50),
	NGUOIYEUCAU_DIACHI NVARCHAR(255),

	NGUOIYEUCAU_QUANHE NVARCHAR(100),

	BANSAO_TEN NVARCHAR(255),
	BANSAO_NGAYSINH DATE,
	BANSAO_GIOITINH BIT,
	BANSAO_QUOCTICH NVARCHAR(50),
	BANSAO_THANHPHO NVARCHAR(50),
	BANSAO_QUAN NVARCHAR(50),
	BANSAO_PHUONG NVARCHAR(50),
	BANSAO_DIACHI NVARCHAR(255),

	LOAI_GIAYTO_ID INT,

	BANSAO_SOQUYEN INT,
	BANSAO_SO INT,

	BANSAO_SOLUONG INT,	 
)
GO
ALTER TABLE DANGKY_TRICHLUC
ADD CONSTRAINT PK_DANGKY_TRICHLUC PRIMARY KEY (HOSO_DANGKY_ID)
GO
ALTER TABLE DANGKY_TRICHLUC
ADD CONSTRAINT FK_DANGKY_TRICHLUC_HOSO_DANG_KY FOREIGN KEY (HOSO_DANGKY_ID) REFERENCES HOSO_DANGKY(HOSO_DANGKY_ID)
GO
ALTER TABLE DANGKY_TRICHLUC
ADD CONSTRAINT FK_DANGKY_TRICHLUC_LOAI_GIAYTO FOREIGN KEY (LOAI_GIAYTO_ID) REFERENCES LOAI_GIAYTO(LOAI_GIAYTO_ID)
GO

-----------------------------------------------------------
CREATE TABLE THONGBAO(
	THONGBAO_ID INT IDENTITY(1,1),
	NGUOIDUNG_ID INT,
	THONGBAO_NOIDUNG NVARCHAR(255),
)
--Tạo bảng trạng thái xử lý
CREATE TABLE TRANGTHAI_XULY(
	TRANGTHAI_XULY_ID INT IDENTITY(1,1),
	TRANGTHAI_XULY_TEN NVARCHAR(255),
)
--Thêm khóa chính và khóa ngoại
ALTER TABLE THONGBAO
ADD CONSTRAINT	PK_THONGBAO PRIMARY KEY (THONGBAO_ID)
GO

--Thêm khóa ngoại cho Thông báo - Người dùng
ALTER TABLE THONGBAO
ADD CONSTRAINT FK_THONGBAO_NGUOIDUNG FOREIGN KEY (NGUOIDUNG_ID) REFERENCES NGUOIDUNG(NGUOIDUNG_ID)
GO

--Thêm khóa ngoại cho Trạng thái - Hồ sơ đăng kí
ALTER TABLE TRANGTHAI_XULY
ADD CONSTRAINT PK_TRANGTHAI_XULY PRIMARY KEY (TRANGTHAI_XULY_ID)
ALTER TABLE HOSO_DANGKY
ADD CONSTRAINT FK_HOSO_DANGKY_TRANGTHAI_XULY FOREIGN KEY (TRANGTHAI_XULY_ID) REFERENCES TRANGTHAI_XULY(TRANGTHAI_XULY_ID)
GO


CREATE TABLE CONGDAN(
	CONGDAN_HOVATEN NVARCHAR(255),
	CONGDAN_NGAYSINH DATE,
	CONGDAN_GIOITINH BIT,
	CONGDAN_QUEQUAN NVARCHAR(50), -- TƯƠNG ỨNG VỚI QUÊ QUÁN THÀNH PHỐ
	CONGDAN_QUOCTICH NVARCHAR(50),
	CONGDAN_DANTOC NVARCHAR(50),
	CONGDAN_CMND NVARCHAR(20),
	CONGDAN_CMND_NGAYCAP DATE,
	CONGDAN_CMND_NOICAP NVARCHAR(255),
	--Địa chỉ công dân, sẽ lấy phần quê quán của giấy khai sinh
	CONGDAN_THANHPHO NVARCHAR(50),
	CONGDAN_QUAN NVARCHAR(50),
	CONGDAN_PHUONG NVARCHAR(50),
	CONGDAN_DIACHI NVARCHAR(255),
	CONGDAN_TINHTRANG_HONNHAN INT,
	CONGDAN_CONSONG BIT,
)
ALTER TABLE CONGDAN
ADD CONGDAN_ID INT IDENTITY(1,1)
ALTER TABLE CONGDAN
ADD CONSTRAINT PK_CONGDAN PRIMARY KEY (CONGDAN_ID)

--Thêm bảng cơ sở dữ liệu của các loại giấy tờ đã được kiểm duyệt thành công
CREATE TABLE GIAY_HOTICH(
	GIAY_HOTICH_ID INT IDENTITY(1,1),
	GIAYTO_ID INT,

	HOSO_DANGKY_ID INT,
	COQUAN_ID INT,
	LOAI_GIAYTO_ID INT,

	GIAY_HOTICH_MA NVARCHAR(10),
	GIAY_HOTICH_SOQUYEN NVARCHAR(10),
	GIAY_HOTICH_NGAY_KY DATETIME,
	GIAY_HOTICH_NGUOI_XULY INT,
	GIAY_HOTICH_NGUOI_KY INT,
)

ALTER TABLE GIAY_HOTICH
ADD CONSTRAINT FK_HOTICH_COQUAN FOREIGN KEY (COQUAN_ID) REFERENCES COQUAN(COQUAN_ID)
GO

--Khai sinh
CREATE TABLE GIAY_KHAISINH(
	GIAY_KHAISINH_ID INT IDENTITY(1,1),
	CONGDAN_ID INT,
	GIAY_KHAISINH_NOISINH NVARCHAR(100), --- Bệnh Viện Từ Vũ /Osinton DC hospital
	GIAY_KHAISINH_NOISINH_QUOCGIA NVARCHAR(50), --- Việt Nam/USA
	GIAY_KHAISINH_NOISINH_THANHPHO NVARCHAR(50), -- Thành phố hồ chính minh /....
	GIAY_KHAISINH_NOISINH_QUAN NVARCHAR(50),---Quận X ....
	GIAY_KHAISINH_NOISINH_PHUONG NVARCHAR(50), ---Phường Y
	GIAY_KHAISINH_NOISINH_DIACHI NVARCHAR(50), --- Số v, Đường L
	CHA_ID INT,
	ME_ID INT,
)
--Kết hôn
CREATE TABLE GIAY_KETHON(
	GIAY_KETHON_ID INT IDENTITY(1,1),
	VO_ID INT,
	CHONG_ID INT,
)
--Chứng tử
CREATE TABLE GIAY_CHUNGTU(
	GIAY_CHUNGTU_ID INT IDENTITY(1,1),
	CONGDAN_ID INT,

	GIAY_CHUNGTU_NGAYMAT DATE,
	GIAY_CHUNGTU_THOIGIAN TIME,

	GIAY_CHUNGTU_NOIMAT_QUOCGIA NVARCHAR(50),
	GIAY_CHUNGTU_NOIMAT_THANHPHO NVARCHAR(50),
	GIAY_CHUNGTU_NOIMAT_QUAN NVARCHAR(50),
	GIAY_CHUNGTU_NOIMAT_PHUONG NVARCHAR(50),
	GIAY_CHUNGTU_NOIMAT_DIACHI NVARCHAR(255),

	GIAY_CHUNGTU_NGUYENNHAN NVARCHAR(255),
)
--Khóa cho Giấy khai sinh
ALTER TABLE GIAY_KHAISINH
ADD CONSTRAINT FK_GIAY_KHAISINH_CON_CONGDAN FOREIGN KEY (CONGDAN_ID) REFERENCES CONGDAN(CONGDAN_ID)
GO
ALTER TABLE GIAY_KHAISINH
ADD CONSTRAINT FK_GIAY_KHAISINH_ME_CONGDAN FOREIGN KEY (ME_ID) REFERENCES CONGDAN(CONGDAN_ID)
GO
ALTER TABLE GIAY_KHAISINH
ADD CONSTRAINT FK_GIAY_KHAISINH_CHA_CONGDAN FOREIGN KEY (CHA_ID) REFERENCES CONGDAN(CONGDAN_ID)
GO
ALTER TABLE GIAY_KHAISINH
ADD CONSTRAINT PK_GIAY_KHAISINH PRIMARY KEY (GIAY_KHAISINH_ID)
--Khóa cho giấy kết hôn
ALTER TABLE GIAY_KETHON
ADD CONSTRAINT FK_GIAY_KETHON_V_CONGDAN FOREIGN KEY (VO_ID) REFERENCES CONGDAN(CONGDAN_ID)
GO
ALTER TABLE GIAY_KETHON
ADD CONSTRAINT FK_GIAY_KETHON_C_CONGDAN FOREIGN KEY (CHONG_ID) REFERENCES CONGDAN(CONGDAN_ID)
GO
ALTER TABLE GIAY_KETHON
ADD CONSTRAINT PK_GIAY_KETHON PRIMARY KEY (GIAY_KETHON_ID)
GO
--Khóa cho giấy chứng tử
ALTER TABLE GIAY_CHUNGTU
ADD CONSTRAINT FK_GIAY_CHUNGTU_CONGDAN FOREIGN KEY (CONGDAN_ID) REFERENCES CONGDAN(CONGDAN_ID)
GO
ALTER TABLE GIAY_CHUNGTU
ADD CONSTRAINT PK_GIAY_CHUNGTU PRIMARY KEY (GIAY_CHUNGTU_ID)
GO

--Khóa cho người xử lý và người ký hộ tịch
ALTER TABLE GIAY_HOTICH
ADD CONSTRAINT FK_GIAY_HOTICH_XULY FOREIGN KEY (GIAY_HOTICH_NGUOI_XULY) REFERENCES NGUOIDUNG(NGUOIDUNG_ID)
GO
ALTER TABLE GIAY_HOTICH
ADD CONSTRAINT FK_GIAY_HOTICH_KY FOREIGN KEY (GIAY_HOTICH_NGUOI_KY) REFERENCES NGUOIDUNG(NGUOIDUNG_ID)
GO

CREATE TABLE PHANHOI(
	PHANHOI_ID INT IDENTITY(1,1),
	HOSO_DANGKY_ID INT,
	PHANHOI_EMAIL NVARCHAR(50),
	PHANHOI_SDT NVARCHAR(20),
	NGUOIDUNG_ID INT,
	PHANHOI_NOIDUNG NVARCHAR(500),
	COQUAN_ID INT,
)
ALTER TABLE PHANHOI
ADD CONSTRAINT PK_PHANHOI PRIMARY KEY (PHANHOI_ID)
ALTER TABLE PHANHOI
ADD CONSTRAINT FK_PHANHOI_NGUOIDUNG FOREIGN KEY (NGUOIDUNG_ID) REFERENCES NGUOIDUNG(NGUOIDUNG_ID)
ALTER TABLE PHANHOI
ADD CONSTRAINT FK_PHANHOI_HOSO_DANGKY FOREIGN KEY (HOSO_DANGKY_ID) REFERENCES HOSO_DANGKY(HOSO_DANGKY_ID)
ALTER TABLE PHANHOI
ADD CONSTRAINT FK_PHANHOI_COQUAN FOREIGN KEY (COQUAN_ID) REFERENCES COQUAN(COQUAN_ID)
GO

CREATE TABLE [dbo].[TRANGTHAI_SUDDUNG](
	[TRANGTHAI_ID] [int] NOT NULL,
	[TRANGTHAI_TEN] [nvarchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[TRANGTHAI_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO



CREATE TABLE [dbo].[QUYEN_SUDUNG](
	[QUYEN_ID] [int] NOT NULL,
	[QUYEN_TEN] [nvarchar](50) NULL,
	[ROLL_TEN] [nvarchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[QUYEN_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO